name: kevchat

services:
  kevchat_client:
    build:
      context: .
      dockerfile: projects/client/Dockerfile-local
      args:
        KEVCHAT_API_URL: http://local.api.kev.chat
        KEVCHAT_CLIENT_URL: http://local.app.kev.chat
        KEVCHAT_FRONT_DOOR_URL: http://local.kev.chat
        KEVCHAT_LOGOUT_URL: http://local.kev.chat
    image: kevchat_client:local
    ports:
      - 3000:3000
      - 9230:9230
    volumes:
      - type: bind
        source: ./projects/client/src
        target: /app/src
      - type: bind
        source: ./projects/client/patches
        target: /app/patches
  mongodb:
    image: mongodb/mongodb-community-server:6.0-ubi8
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pass
    ports:
      - 27017:27017
    volumes:
      - type: bind
        source: ./data
        target: /data/db
  kevchat_api:
    build:
      context: .
      dockerfile: projects/api/Dockerfile-local
    image: kevchat_api:local
    ports:
      - 5000:5000
      - 9229:9229
    environment:
      - CONN_STR=mongodb://user:pass@mongodb
    volumes:
      - type: bind
        source: ./projects/api/src
        target: /app/src
  local_proxy:
    build:
      context: .
      dockerfile: projects/local-proxy/Dockerfile
    image: kevchat_local_proxy:local
    ports:
      - 80:80
  kevchat_front_door:
    build:
      context: .
      dockerfile: projects/front-door/Dockerfile
      args:
        KEVCHAT_CLIENT_URL: http://local.app.kev.chat
    image: kevchat_front_door:local
    ports:
      - 8080:8080
