name: kevchat

services:
  kevchat_client:
    build:
      context: .
      dockerfile: projects/client/Dockerfile
      args:
        KEVCHAT_API_URL: https://api.kev.chat
        KEVCHAT_CLIENT_URL: https://app.kev.chat
        KEVCHAT_FRONT_DOOR_URL: https://kev.chat
        KEVCHAT_LOGOUT_URL: https://kevchat.auth.us-east-2.amazoncognito.com/logout?logout_uri=https%3A%2F%2Fkev.chat&client_id=1g2fva2c3i0e2sdkumksmv7m8
    image: kevchat_client:0.5.0
  kevchat_api:
    build:
      context: .
      dockerfile: projects/api/Dockerfile
    image: kevchat_api:0.3.0