name: kevchat

services:
  kevchat_client:
    build:
      context: .
      dockerfile: projects/client/Dockerfile-local
      args:
        KEVCHAT_API_URL: ${KEVCHAT_API_URL}
        KEVCHAT_CLIENT_URL: ${KEVCHAT_CLIENT_URL}
        KEVCHAT_FRONT_DOOR_URL: ${KEVCHAT_FRONT_DOOR_URL}
    image: kevchat_client:${KEVCHAT_ENV}
    environment:
      - KEVCHAT_API_URL=${KEVCHAT_API_URL}
      - KEVCHAT_CLIENT_PORT=${KEVCHAT_CLIENT_PORT}
      - KEVCHAT_CLIENT_LOGIN_URL=${KEVCHAT_CLIENT_LOGIN_URL}
      - KEVCHAT_CLIENT_LOGOUT_URL=${KEVCHAT_CLIENT_LOGOUT_URL}
      - KEVCHAT_FRONT_DOOR_URL=${KEVCHAT_FRONT_DOOR_URL}
      - KEVCHAT_CLIENT_AUTH_LOGIN_CALLBACK_URL=${KEVCHAT_CLIENT_AUTH_LOGIN_CALLBACK_URL}
      - KEVCHAT_CLIENT_URL=${KEVCHAT_CLIENT_URL}
      - KEVCHAT_IDP_OIDC_TOKEN_URL=${KEVCHAT_IDP_OIDC_TOKEN_URL}
    healthcheck:
      test:
        [
          'CMD-SHELL',
          "sh -c 'until curl -f ${KEVCHAT_CLIENT_INTERNAL_HOST}:${KEVCHAT_CLIENT_PORT}/healthz; do sleep 1; done;'",
        ]
      start_period: 30s
      start_interval: 5s
    ports:
      - ${KEVCHAT_CLIENT_DEBUG_PORT_PRIMARY}:${KEVCHAT_CLIENT_DEBUG_PORT_PRIMARY} 
      - ${KEVCHAT_CLIENT_DEBUG_PORT_SECONDARY}:${KEVCHAT_CLIENT_DEBUG_PORT_SECONDARY}
    volumes:
      - type: bind
        source: ./projects/client/src
        target: /app/src
      - type: bind
        source: ./projects/client/.next
        target: /app/.next
  mongodb:
    build:
      context: .
      dockerfile: Mongo.Dockerfile
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      - MONGO_PORT=${MONGO_PORT}
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test:
        ['CMD-SHELL', "sh -c 'until nc -z mongodb ${MONGO_PORT}; do sleep 1; done;'"]
      start_period: 30s
      start_interval: 5s
  init_mongodb:
    image: mongo:8.0.6
    depends_on:
      mongodb:
        restart: true
        condition: service_healthy
    # command: tail -f /dev/null
    command: mongosh "mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@mongodb:${MONGO_PORT}/admin" -f /app/initMongo.js
    environment:
      - MONGO_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      - MONGO_PORT=${MONGO_PORT}
      - DB_API_USERNAME=${DB_API_USERNAME}
      - DB_API_PASSWORD=${DB_API_PASSWORD}
      - DB_IDP_USERNAME=${DB_IDP_USERNAME}
      - DB_IDP_PASSWORD=${DB_IDP_PASSWORD}
      - DB_APP_NAME=${DB_APP_NAME}
      - DB_IDP_NAME=${DB_IDP_NAME}
    volumes:
      - type: bind
        source: ./projects/scripts
        target: /app
  kevchat_api:
    build:
      context: .
      dockerfile: projects/api/Dockerfile-local
    image: kevchat_api:${KEVCHAT_ENV}
    depends_on:
      init_kafka:
        condition: service_completed_successfully
      init_mongodb:
        condition: service_completed_successfully
    ports:
      - ${KEVCHAT_API_DEBUG_PORT}:${KEVCHAT_API_DEBUG_PORT}
    environment:
      - MONGO_CONNECTION_STRING=mongodb://${DB_API_USERNAME}:${DB_API_PASSWORD}@mongodb:${MONGO_PORT}/${DB_APP_NAME}
      - KEVCHAT_API_PORT=${KEVCHAT_API_PORT}
      - KEVCHAT_API_DEBUG_PORT=${KEVCHAT_API_DEBUG_PORT}
      - KEVCHAT_IDP_USER_UPSERT_TOPIC_NAME=${KEVCHAT_IDP_USER_UPSERT_TOPIC_NAME}
      - KAFKA_BROKERS=kafka:${KAFKA_INTERNAL_LISTENER_PORT}
      - KAFKA_CLIENT_ID=activity-log-api
      - KAFKA_CONSUMER_GROUP_ID=activity-log-api
      - KAFKAJS_NO_PARTITIONER_WARNING=1
    volumes:
      - type: bind
        source: ./projects/api/src
        target: /app/src
      - type: bind
        source: ./projects/api/dist
        target: /app/dist
    healthcheck:
      test:
        [
          'CMD-SHELL',
          "sh -c 'until curl -f ${KEVCHAT_API_INTERNAL_HOST}:${KEVCHAT_API_PORT}/healthz; do sleep 1; done;'",
        ]
      start_period: 30s
      start_interval: 5s
  proxy:
    build:
      context: .
      dockerfile: projects/proxy/Dockerfile
      args:
        - KEVCHAT_ENV=${KEVCHAT_ENV}
        - KEVCHAT_IDP_INTERNAL_HOST=${KEVCHAT_IDP_INTERNAL_HOST}
        - KEVCHAT_API_INTERNAL_HOST=${KEVCHAT_API_INTERNAL_HOST}
        - KEVCHAT_CLIENT_INTERNAL_HOST=${KEVCHAT_CLIENT_INTERNAL_HOST}
        - KEVCHAT_FRONT_DOOR_INTERNAL_HOST=${KEVCHAT_FRONT_DOOR_INTERNAL_HOST}
        - KEVCHAT_IDP_PORT=${KEVCHAT_IDP_PORT}
        - KEVCHAT_API_PORT=${KEVCHAT_API_PORT}
        - KEVCHAT_CLIENT_PORT=${KEVCHAT_CLIENT_PORT}
        - KEVCHAT_FRONT_DOOR_PORT=${KEVCHAT_FRONT_DOOR_PORT}
        - KEVCHAT_CLIENT_URL=${KEVCHAT_CLIENT_URL}
        - KEVCHAT_SOCKET_IO_ADMIN_URL=${KEVCHAT_SOCKET_IO_ADMIN_URL}
        - KEVCHAT_KAFKA_UI_INTERNAL_HOST=${KEVCHAT_KAFKA_UI_INTERNAL_HOST}
        - KEVCHAT_KAFKA_UI_PORT=${KEVCHAT_KAFKA_UI_PORT}
        - KEVCHAT_SOCKET_IO_ADMIN_INTERNAL_HOST=${KEVCHAT_SOCKET_IO_ADMIN_INTERNAL_HOST}
        - KEVCHAT_SOCKET_IO_ADMIN_PORT=${KEVCHAT_SOCKET_IO_ADMIN_PORT}
    image: kevchat_proxy:${KEVCHAT_ENV}
    # command: tail -f /dev/null
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./projects/proxy/certs:/etc/nginx/certs:ro
    develop:
      watch:
        - action: rebuild
          path: ./projects/proxy/nginx.conf
          target: /etc/nginx/nginx.conf
        - action: rebuild
          path: ./projects/proxy/nginx.conf
          target: /etc/nginx/nginx.conf
        - action: rebuild
          path: ./projects/includes
          target: /etc/nginx/includes
    depends_on:
      kevchat_api:
        condition: service_healthy
      kevchat_front_door:
        condition: service_healthy
      kevchat_client:
        condition: service_healthy
      kevchat_idp:
        condition: service_healthy
      socket_io_admin:
        condition: service_healthy
      kafka_ui:
        condition: service_healthy
  kevchat_front_door:
    build:
      context: .
      dockerfile: projects/front-door/Dockerfile
      args:
        KEVCHAT_CLIENT_URL: https://${KEVCHAT_ENV}.app.kev.chat
    image: kevchat_front_door:${KEVCHAT_ENV}
    environment:
      - KEVCHAT_FRONT_DOOR_PORT=${KEVCHAT_FRONT_DOOR_PORT}
      - KEVCHAT_FRONT_DOOR_GET_STARTED_URL=${KEVCHAT_FRONT_DOOR_GET_STARTED_URL}
    volumes:
      - type: bind
        source: ./projects/front-door/src
        target: /app/src
      - type: bind
        source: ./projects/front-door/.next
        target: /app/.next
    healthcheck:
      test:
        [
          'CMD-SHELL',
          "sh -c 'until curl -f ${KEVCHAT_FRONT_DOOR_INTERNAL_HOST}:${KEVCHAT_FRONT_DOOR_PORT}/healthz; do sleep 1; done;'",
        ]
      start_period: 30s
      start_interval: 5s
  kevchat_idp:
    build:
      context: .
      dockerfile: projects/idp/Dockerfile-local
    image: kevchat_idp:${KEVCHAT_ENV}
    depends_on:
      init_kafka:
        condition: service_completed_successfully
      init_mongodb:
        condition: service_completed_successfully
    healthcheck:
      test:
        [
          'CMD-SHELL',
          "sh -c 'until curl -f ${KEVCHAT_IDP_INTERNAL_HOST}:${KEVCHAT_IDP_PORT}/healthz; do sleep 1; done;'",
        ]
      start_period: 30s
      start_interval: 5s
    ports:
      - ${KEVCHAT_IDP_DEBUG_PORT}:${KEVCHAT_IDP_DEBUG_PORT}
    environment:
      - KAFKAJS_NO_PARTITIONER_WARNING=1
      - KAFKA_BROKERS=kafka:${KAFKA_INTERNAL_LISTENER_PORT}
      - KAFKA_CLIENT_ID=activity-log-idp
      - KAFKA_CONSUMER_GROUP_ID=activity-log
      - KAKFA_USE_SSL=false
      - KEVCHAT_CLIENT_AUTH_LOGIN_CALLBACK_URL=${KEVCHAT_CLIENT_AUTH_LOGIN_CALLBACK_URL}
      - KEVCHAT_CLIENT_AUTH_LOGOUT_CALLBACK_URL=${KEVCHAT_CLIENT_AUTH_LOGOUT_CALLBACK_URL}
      - KEVCHAT_IDP_BASE_URL=${KEVCHAT_IDP_BASE_URL}
      - KEVCHAT_IDP_DEBUG_PORT=${KEVCHAT_IDP_DEBUG_PORT}
      - KEVCHAT_IDP_OIDC_SESSION_COOKIE_KEY=${KEVCHAT_IDP_OIDC_SESSION_COOKIE_KEY}
      - KEVCHAT_IDP_PORT=${KEVCHAT_IDP_PORT}
      - KEVCHAT_IDP_SESSION_COOKIE_KEY=${KEVCHAT_IDP_SESSION_COOKIE_KEY}
      - MONGO_CONNECTION_STRING=mongodb://${DB_IDP_USERNAME}:${DB_IDP_PASSWORD}@mongodb:${MONGO_PORT}/${DB_IDP_NAME}
      - KEVCHAT_IDP_USER_UPSERT_TOPIC_NAME=${KEVCHAT_IDP_USER_UPSERT_TOPIC_NAME}
      - KEVCHAT_IDP_ALLOWED_CANCEL_REDIRECT_DOMAINS=${KEVCHAT_IDP_ALLOWED_CANCEL_REDIRECT_DOMAINS}
      - KEVCHAT_IDP_ALLOWED_OIDC_AUTH_REDIRECT_DOMAINS=${KEVCHAT_IDP_ALLOWED_OIDC_AUTH_REDIRECT_DOMAINS}
      - KEVCHAT_IDP_ALLOWED_SIGNUP_REDIRECT_DOMAINS=${KEVCHAT_IDP_ALLOWED_SIGNUP_REDIRECT_DOMAINS}
    volumes:
      - type: bind
        source: ./projects/idp/data
        target: /app/data
      - type: bind
        source: ./projects/idp/src
        target: /app/src
      - type: bind
        source: ./projects/idp/dist
        target: /app/dist
      - type: bind
        source: ./projects/idp/views
        target: /app/views
      - type: bind
        source: ./projects/idp/public
        target: /app/public
  kafka:
    image: confluentinc/cp-kafka:7.5.0
    healthcheck:
      test:
        [
          'CMD-SHELL',
          "sh -c 'until kafka-topics --bootstrap-server kafka:${KAFKA_INTERNAL_LISTENER_PORT} --list; do sleep 1; done;'",
        ]
      start_period: 30s
      start_interval: 5s
    ports:
      - "${KAFKA_EXTERNAL_LISTENER_PORT}:${KAFKA_EXTERNAL_LISTENER_PORT}"
    environment:
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      CLUSTER_ID: A9-by2cjSNaqPbwb-bfkCA
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: >
        INTERNAL:PLAINTEXT,
        EXTERNAL:PLAINTEXT,
        CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:${KAFKA_CONTROLLER_LISTENER_PORT}
      KAFKA_LISTENERS: >
        INTERNAL://0.0.0.0:${KAFKA_INTERNAL_LISTENER_PORT},
        EXTERNAL://0.0.0.0:${KAFKA_EXTERNAL_LISTENER_PORT},
        CONTROLLER://:${KAFKA_CONTROLLER_LISTENER_PORT}
      KAFKA_ADVERTISED_LISTENERS: >
        INTERNAL://kafka:${KAFKA_INTERNAL_LISTENER_PORT},
        EXTERNAL://localhost:${KAFKA_EXTERNAL_LISTENER_PORT},
    volumes:
      - kafka_data:/var/lib/kafka/data
  init_kafka:
    image: confluentinc/cp-kafka:7.5.0
    restart: on-failure:5
    depends_on:
      kafka:
        condition: service_healthy
    environment:
      - KAFKA_INTERNAL_LISTENER_PORT=${KAFKA_INTERNAL_LISTENER_PORT}
      - KAFKA_HOST=kafka
      - KEVCHAT_IDP_USER_UPSERT_TOPIC_NAME=${KEVCHAT_IDP_USER_UPSERT_TOPIC_NAME}
    volumes:
      - ./projects/scripts:/scripts
    entrypoint: ["sh", "/scripts/create-kafka-topics.sh"]
  kafka_ui:
    build:
      context: .
      dockerfile: KafkaUI.Dockerfile
    # container_name: kevchat_kafka_ui
    ports:
      - 8888:8080
    environment:
      - KAFKA_CLUSTERS_0_NAME=kevchat
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:${KAFKA_INTERNAL_LISTENER_PORT}
    depends_on:
      init_kafka:
        condition: service_completed_successfully
    healthcheck:
      test:
        [
          'CMD-SHELL',
          "sh -c 'until curl -f http://${KEVCHAT_KAFKA_UI_INTERNAL_HOST}:${KEVCHAT_KAFKA_UI_PORT}; do sleep 1; done;'",
        ]
      start_period: 30s
      start_interval: 5s
  socket_io_admin:
    build:
      context: .
      dockerfile: SocketIOAdmin.Dockerfile
      args:
        - KEVCHAT_SOCKET_IO_ADMIN_PORT=${KEVCHAT_SOCKET_IO_ADMIN_PORT}
    # command: tail -f /dev/null
    healthcheck:
      test:
        [
          'CMD-SHELL',
          "sh -c 'until curl -f http://${KEVCHAT_SOCKET_IO_ADMIN_INTERNAL_HOST}:${KEVCHAT_SOCKET_IO_ADMIN_PORT}; do sleep 1; done;'",
        ]
      start_period: 30s
      start_interval: 5s
volumes:
  kafka_data:
  mongo_data:
