# Base image
FROM node:22

# Create app directory
WORKDIR /app

COPY projects/api/package.json package-lock.json ./

# Install app dependencies
RUN npm i

# Bundle app source
COPY ./projects/api .

# Expose the port on which the app will run
EXPOSE 5000

# Expose debug port
EXPOSE 9229

# Start the server using the debug build
CMD ["npm", "run", "start:debug"]