# Base image
FROM node:22

ARG KEVCHAT_API_URL
ARG KEVCHAT_CLIENT_URL
ARG KEVCHAT_FRONT_DOOR_URL

ENV NEXT_PUBLIC_KEVCHAT_API_URL=${KEVCHAT_API_URL}
ENV NEXT_PUBLIC_KEVCHAT_CLIENT_URL=${KEVCHAT_CLIENT_URL}
ENV NEXT_PUBLIC_KEVCHAT_FRONT_DOOR_URL=${KEVCHAT_FRONT_DOOR_URL}
ENV WATCHPACK_POLLING=true

# Create app directory
WORKDIR /app

COPY projects/client/package.json package-lock.json ./

# Install app dependencies
RUN npm i

# Bundle app source
COPY ./projects/client .

# Expose the port on which the app will run
EXPOSE 3000

# Expose debug port
EXPOSE 9230

# ENV NODE_OPTIONS="--inspect=0.0.0.0:9229"

# Start the server using the debug build
CMD ["npm", "run", "dev"]